[package]
name = "preconfirmation-gateway"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "commitments"
path = "commitments.rs"

[[bin]]
name = "constraints"
path = "constraints.rs"

[dependencies]
common = { path = "../crates/common" }
commitments = { path = "../crates/commitments" }
constraints = { path = "../crates/constraints" }
anyhow = { workspace = true }
eyre = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
commit-boost = { workspace = true }

# todo eventually remove
cb-common = { git = "https://github.com/Commit-Boost/commit-boost-client", branch = "fabric" }
