[package]
name = "preconfirmation-gateway"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "commitments"
path = "commitments.rs"

[dependencies]
common = { path = "../crates/common" }
commitments = { path = "../crates/commitments" }
anyhow = { workspace = true }
eyre = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
commit-boost = { workspace = true }
