[package]
name = "preconfirmation-gateway"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gateway"
path = "gateway.rs"

[[bin]]
name = "relay"
path = "relay.rs"

[[bin]]
name = "proposer"
path = "proposer.rs"

[dependencies]
common = { path = "../crates/common" }
commitments = { path = "../crates/commitments" }
constraints = { path = "../crates/constraints" }
gateway = { path = "../crates/gateway" }
relay = { path = "../crates/relay" }
proposer = { path = "../crates/proposer" }
rocksdb = { workspace = true }
anyhow = { workspace = true }
eyre = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
commit-boost = { workspace = true }

# todo eventually remove
cb-common = { git = "https://github.com/Commit-Boost/commit-boost-client", branch = "fabric" }
