[package]
name = "preconfirmation-gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
eyre = "0.6"
config = "0.15.15"
deadpool-postgres = "0.14.1"
futures = "0.3.31"
http-body = "1.0.1"
http-body-util = "0.1.3"
jsonrpsee = { version = "0.26.0", features = ["http-client", "server", "client-core"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread", "macros"] }
tokio-postgres = "0.7.13"
toml = "0.9.5"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
alloy = { version = "^1.0.35", features = [
    "full",
    "getrandom",
    "providers",
    "rpc-types-beacon",
    "serde",
    "signer-local",
    "ssz",
] }
alloy-primitives = "^1.3.1"
commit-boost = { git = "https://github.com/Commit-Boost/commit-boost-client", branch = "fabric" }

[patch.crates-io]
blstrs_plus = { git = "https://github.com/Commit-Boost/blstrs" }

[dev-dependencies]
serde_json = "1.0"
tempfile = "3.8"
tokio-test = "0.4"
