[package]
name = "preconfirmation-gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
futures = "0.3.31"
http-body = "1.0.1"
http-body-util = "0.1.3"
jsonrpsee = { version = "0.26.0", features = ["http-client", "server", "client-core"] }
postgres = "0.19.10"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread", "macros"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }

[dev-dependencies]
serde_json = "1.0"
tokio-test = "0.4"
