[package]
name = "preconfirmation-gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
futures = "0.3.31"
http-body = "1.0.1"
http-body-util = "0.1.3"
jsonrpsee = "0.26.0"
tokio = "1.47.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
