# Proposer Configuration
# This file contains configuration settings for the preconfirmation proposer service

# Chain configuration
chain = "Hoodi"

# PBS (Proposer-Builder Separation) configuration
[pbs]
port = 18550
with_signer = true

# Relays configuration
[[relays]]
url = "https://0xafa4c6985aa049fb79dd37010438cfebeb0f2bd42b115b89dd678dab0670c1de38da0c4e9138c9290a398ecd9a0b3110@boost-relay-hoodi.flashbots.net"

# Metrics configuration
[metrics]
enabled = true

# Signer configuration
[signer]
port = 20000

[signer.local.loader]
format = "lighthouse"
keys_path = "./tests/data/keystores/keys"
secrets_path = "./tests/data/keystores/secrets"

[signer.local.store]
proxy_dir = "./tests/data/proxy"

# Proposer Module configuration
[[modules]]
id = "proposer-module"
signing_id = "0x2222222222222222222222222222222222222222222222222222222222222222"
type = "commit"
docker_image = "todo"
env_file = ".cb.env"

# Proposer service configuration

# This is a BLS proxy key for the gateway to sign constraints
delegate_bls_public_key = "0xa6bf34f124537d044446171c7ad042eab8c605bdce05cdf161c94ccb8809fd7a394cd87780ceddaa497a3a4f5948cb1c"
# This is an ECDSA address for the gateway to sign commitments
committer_address = "0x73892d18EACa21E8C1Aca89c147069C9D9f6625D"
relay_url = "http://localhost:9999"
relay_api_key = ""
beacon_api_url = "http://localhost:5052"
beacon_genesis_timestamp = 1606824023 # mainnet
poll_interval_seconds = 12
module_signing_id = "0x2222222222222222222222222222222222222222222222222222222222222222"

# URC Registration Configuration
urc_owner = "0xBB771250f7CA20123AA4c4175a49fdD8774838F3"
execution_rpc_url = "http://localhost:8545"
registration_collateral_wei = "1000000000000000000"

