[relay]
port = 8080
database_path = "data/relay-rocksdb"
log_level = "info"
constraint_capabilities = [1]
chain = "Hoodi"
genesis_timestamp = 1742213400

[storage]
max_delegations_per_slot = 100
max_constraints_per_slot = 1000
