[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
eyre = { workspace = true }
config = { workspace = true }
rocksdb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
alloy = { workspace = true }
alloy-primitives = { workspace = true }
commit-boost = { workspace = true }

[dev-dependencies]
tempfile = "3.8"
tokio-test = "0.4"
rand = "0.8"
cb-tests = { git = "https://github.com/Commit-Boost/commit-boost-client", branch = "fabric" }
cb-common = { git = "https://github.com/Commit-Boost/commit-boost-client", branch = "fabric" }
cb-signer = { git = "https://github.com/Commit-Boost/commit-boost-client", branch = "fabric" }
reqwest = { version = "0.12.4", features = ["json", "rustls-tls"] }
